CREATE TABLE IF NOT EXISTS reward (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    points INT NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    image_url VARCHAR(255),
    expired_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);