CREATE TABLE IF NOT EXISTS redeem (
    id VARCHAR(255) PRIMARY KEY,
    organization_id VARCHAR(255),
    customer_id VARCHAR(255) NOT NULL,
    reward_id VARCHAR(255) NOT NULL,
    redemption_date TIMESTAMP WITH TIME ZONE NOT NULL,
    points_redeemed INT NOT NULL,
    redemption_code VARCHAR(255) UNIQUE,
    status VARCHAR(50) DEFAULT 'PENDING',
    address TEXT,
    province_id VARCHAR(255),
    regency_id VARCHAR(255), 
    district_id VARCHAR(255),
    village_id VARCHAR(255),
    rt VARCHAR(10),
    rw VARCHAR(10),
    postal_code VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);
